# Generated by Django 5.1.4 on 2026-08-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField(db_index=True, unique=True)),
                ("count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Visite du site",
                "verbose_name_plural": "Visites du site",
                "ordering": ["-date"],
            },
        ),
    ]
