# Generated by Django 5.1.4 on 2026-07-23 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_pushsubscription"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "welcome_message",
                    models.TextField(
                        default="Bienvenue sur SPORTI ! Nous sommes ravis de vous compter parmi nous. Rejoignez nos canaux officiels pour toute question ou mise à jour."
                    ),
                ),
                (
                    "telegram_url",
                    models.URLField(
                        blank=True, help_text="Lien Telegram du gestionnaire", null=True
                    ),
                ),
                (
                    "whatsapp_url",
                    models.URLField(blank=True, help_text="Lien de la chaîne WhatsApp", null=True),
                ),
            ],
            options={
                "verbose_name": "Configuration de l'application",
                "verbose_name_plural": "Configurations de l'application",
            },
        ),
    ]
