# Generated by Django 5.1.4 on 2026-08-04 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_pushsubscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Photo de profil personnalisee, choisie par l'utilisateur.",
                null=True,
                upload_to="avatars/",
            ),
        ),
    ]
