# Generated by Django 5.1.4 on 2026-07-17 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companyprofile",
            name="description",
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="description_en",
            field=models.TextField(blank=True, verbose_name="Description (Anglais)"),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="description_fr",
            field=models.TextField(blank=True, verbose_name="Description (Francais)"),
        ),
        migrations.AlterField(
            model_name="welcomemessage",
            name="text_en",
            field=models.TextField(blank=True, verbose_name="Message (Anglais)"),
        ),
        migrations.AlterField(
            model_name="welcomemessage",
            name="text_fr",
            field=models.TextField(verbose_name="Message (Francais)"),
        ),
    ]
