# Generated by Django 5.1.4 on 2026-07-24 18:15

from django.db import migrations, models


def enable_existing_media(apps, schema_editor):
    """Les messages d'accueil deja crees avant ce correctif peuvent avoir
    un fichier audio/video televerse mais jamais active -- on les
    reactive ici pour ne pas laisser un vocal deja en place invisible."""
    WelcomeMessage = apps.get_model("company", "WelcomeMessage")
    WelcomeMessage.objects.filter(audio_file__gt="").update(is_audio_enabled=True)
    WelcomeMessage.objects.filter(video_file__gt="").update(is_video_enabled=True)


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0002_remove_companyprofile_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="welcomemessage",
            name="is_audio_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="welcomemessage",
            name="is_video_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(enable_existing_media, migrations.RunPython.noop),
    ]
