# Generated by Django 5.1.4 on 2026-07-24 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0003_alter_welcomemessage_is_audio_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="externallink",
            name="category",
            field=models.CharField(
                choices=[("social", "Reseau social"), ("platform", "Plateforme recommandee")],
                default="social",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="externallink",
            name="promo_code",
            field=models.CharField(blank=True, max_length=30, verbose_name="Code promo"),
        ),
    ]
